// =============================================================================
// Guildmaster SFX populate script (spec impl 09, package 1). GENERATED by
// scratchpad/build_populate.py from manifest.json — edit the manifest, regen.
//
// Builds one FMOD event per manifest entry: round-robin multi-instrument from the
// listed audio files, assigned to the SFX bank. Idempotent (same event path is
// rebuilt on re-run). Headless-safe: NO modal dialogs (they hang fmodstudiocl);
// all output goes to populate_log.txt.
//
// RUN (headless, two commands — populate then build):
//   fmodstudiocl.exe -script "FMOD Project/Tooling/populate.js" "FMOD Project/Guildmaster Autobattler Game.fspro"
//   fmodstudiocl.exe -build -ignore-warnings -export-guids "FMOD Project/Guildmaster Autobattler Game.fspro"
// populate.js lives in Tooling/ (NOT Scripts/) so FMOD does not auto-run it on every project load.
//
// RELIABLE: events, round-robin multi-instruments, bank assignment, max instances.
// BEST-EFFORT (wrapped, never aborts): buses, output routing.
// GUI PASS (spec 09 P6, by ear + Live Update): pitch/volume Random modulators,
// cooldown, stealing/priority, sidechain, TimeScale->SFX_Combat pitch curve.
// =============================================================================

(function () {
    'use strict';

    var LOG_PATH = "C:/My Projects/Guildmaster-Autobattler/FMOD Project/Scripts/populate_log.txt";
    var MANIFEST = {
  "sourceRoot": "C:/My Program Files/_TEMP/SFX",
  "bank": "SFX",
  "buses": {
    "SFX_Combat": "bus:/SFX_Combat",
    "SFX_UI": "bus:/SFX_UI",
    "Stingers": "bus:/Stingers"
  },
  "categories": {
    "impact": {
      "bus": "SFX_Combat",
      "pitchSemitones": 2.5,
      "volumeDb": 3.0,
      "maxInstances": 4,
      "cooldownMs": 60,
      "stealing": "quietest",
      "priority": "low"
    },
    "whoosh": {
      "bus": "SFX_Combat",
      "pitchSemitones": 1.5,
      "volumeDb": 3.0,
      "maxInstances": 4,
      "cooldownMs": 60,
      "stealing": "quietest",
      "priority": "low"
    },
    "tonal": {
      "bus": "SFX_Combat",
      "pitchSemitones": 0.5,
      "volumeDb": 2.0,
      "maxInstances": 3,
      "cooldownMs": 50,
      "stealing": "virtualize",
      "priority": "medium"
    },
    "cast": {
      "bus": "SFX_Combat",
      "pitchSemitones": 1.0,
      "volumeDb": 2.0,
      "maxInstances": 2,
      "cooldownMs": 50,
      "stealing": "virtualize",
      "priority": "medium"
    },
    "death": {
      "bus": "SFX_Combat",
      "pitchSemitones": 2.0,
      "volumeDb": 3.0,
      "maxInstances": 3,
      "cooldownMs": 80,
      "stealing": "oldest",
      "priority": "high"
    },
    "stinger": {
      "bus": "Stingers",
      "pitchSemitones": 0.0,
      "volumeDb": 1.0,
      "maxInstances": 1,
      "cooldownMs": 0,
      "stealing": "none",
      "priority": "highest"
    },
    "ui": {
      "bus": "SFX_UI",
      "pitchSemitones": 1.0,
      "volumeDb": 2.0,
      "maxInstances": 2,
      "cooldownMs": 30,
      "stealing": "oldest",
      "priority": "high"
    }
  },
  "events": [
    {
      "key": "attack",
      "action": "Attack",
      "isDefault": true,
      "path": "event:/SFX/Combat/attack",
      "category": "whoosh",
      "files": [
        "RPG_Essentials_Free/10_Battle_SFX/22_Slash_04.wav",
        "RPG_Essentials_Free/12_Player_Movement_SFX/56_Attack_03.wav"
      ]
    },
    {
      "key": "fire",
      "action": "Fire",
      "isDefault": true,
      "path": "event:/SFX/Combat/fire",
      "category": "whoosh",
      "files": [
        "RPG_Essentials_Free/8_Atk_Magic_SFX/25_Wind_01.wav"
      ]
    },
    {
      "key": "hit",
      "action": "Hit",
      "isDefault": true,
      "path": "event:/SFX/Combat/hit",
      "category": "impact",
      "files": [
        "kenney_impact-sounds/Audio/impactPunch_medium_000.ogg",
        "kenney_impact-sounds/Audio/impactPunch_medium_001.ogg",
        "kenney_impact-sounds/Audio/impactPunch_medium_002.ogg",
        "kenney_impact-sounds/Audio/impactPunch_medium_003.ogg",
        "kenney_impact-sounds/Audio/impactPunch_medium_004.ogg",
        "RPG_Essentials_Free/10_Battle_SFX/15_Impact_flesh_02.wav",
        "RPG_Essentials_Free/10_Battle_SFX/77_flesh_02.wav"
      ]
    },
    {
      "key": "evade",
      "action": "Evade",
      "isDefault": true,
      "path": "event:/SFX/Combat/evade",
      "category": "whoosh",
      "files": [
        "RPG_Essentials_Free/10_Battle_SFX/35_Miss_Evade_02.wav"
      ]
    },
    {
      "key": "shield",
      "action": "Shield",
      "isDefault": true,
      "path": "event:/SFX/Combat/shield",
      "category": "impact",
      "files": [
        "kenney_impact-sounds/Audio/impactMetal_medium_000.ogg",
        "kenney_impact-sounds/Audio/impactMetal_medium_001.ogg",
        "kenney_impact-sounds/Audio/impactMetal_medium_002.ogg",
        "kenney_impact-sounds/Audio/impactMetal_medium_003.ogg",
        "kenney_impact-sounds/Audio/impactMetal_medium_004.ogg",
        "RPG_Essentials_Free/10_Battle_SFX/39_Block_03.wav"
      ]
    },
    {
      "key": "heal",
      "action": "Heal",
      "isDefault": true,
      "path": "event:/SFX/Combat/heal",
      "category": "tonal",
      "files": [
        "RPG_Essentials_Free/8_Buffs_Heals_SFX/02_Heal_02.wav"
      ]
    },
    {
      "key": "cast",
      "action": "Cast",
      "isDefault": true,
      "path": "event:/SFX/Combat/cast",
      "category": "cast",
      "files": [
        "RPG_Essentials_Free/8_Atk_Magic_SFX/45_Charge_05.wav"
      ]
    },
    {
      "key": "death",
      "action": "Death",
      "isDefault": true,
      "path": "event:/SFX/Combat/death",
      "category": "death",
      "files": [
        "kenney_impact-sounds/Audio/impactSoft_heavy_000.ogg",
        "kenney_impact-sounds/Audio/impactSoft_heavy_001.ogg",
        "kenney_impact-sounds/Audio/impactSoft_heavy_002.ogg",
        "kenney_impact-sounds/Audio/impactSoft_heavy_003.ogg",
        "kenney_impact-sounds/Audio/impactSoft_heavy_004.ogg",
        "RPG_Essentials_Free/10_Battle_SFX/69_Enemy_death_01.wav"
      ]
    },
    {
      "key": "apply",
      "action": "Apply",
      "isDefault": true,
      "path": "event:/SFX/Combat/apply",
      "category": "tonal",
      "files": [
        "RPG_Essentials_Free/8_Buffs_Heals_SFX/16_Atk_buff_04.wav",
        "RPG_Essentials_Free/8_Buffs_Heals_SFX/17_Def_buff_01.wav"
      ]
    },
    {
      "key": "expire",
      "action": "Expire",
      "isDefault": true,
      "path": "event:/SFX/Combat/expire",
      "category": "tonal",
      "files": [
        "RPG_Essentials_Free/8_Buffs_Heals_SFX/21_Debuff_01.wav"
      ]
    },
    {
      "key": "tick",
      "action": "Tick",
      "isDefault": true,
      "path": "event:/SFX/Combat/tick",
      "category": "tonal",
      "files": [
        "RPG_Essentials_Free/8_Atk_Magic_SFX/46_Poison_01.wav"
      ]
    },
    {
      "key": "ui",
      "action": "Ui",
      "isDefault": true,
      "path": "event:/SFX/UI/ui",
      "category": "ui",
      "files": [
        "RPG_Essentials_Free/10_UI_Menu_SFX/013_Confirm_03.wav"
      ]
    },
    {
      "key": "stinger",
      "action": "Stinger",
      "isDefault": true,
      "path": "event:/Stingers/stinger",
      "category": "stinger",
      "files": [
        "RPG_Essentials_Free/10_Battle_SFX/55_Encounter_02.wav"
      ]
    },
    {
      "key": "relic.cryomancer.attack",
      "isDefault": false,
      "path": "event:/SFX/Relics/cryomancer/attack",
      "category": "tonal",
      "files": [
        "RPG_Essentials_Free/8_Atk_Magic_SFX/13_Ice_explosion_01.wav"
      ]
    },
    {
      "key": "relic.cryomancer.cast",
      "isDefault": false,
      "path": "event:/SFX/Relics/cryomancer/cast",
      "category": "cast",
      "files": [
        "RPG_Essentials_Free/8_Atk_Magic_SFX/13_Ice_explosion_01.wav",
        "RPG_Essentials_Free/8_Atk_Magic_SFX/45_Charge_05.wav"
      ]
    },
    {
      "key": "effect.frozen.apply",
      "isDefault": false,
      "path": "event:/SFX/Effects/frozen/apply",
      "category": "tonal",
      "files": [
        "RPG_Essentials_Free/8_Atk_Magic_SFX/13_Ice_explosion_01.wav"
      ]
    },
    {
      "key": "effect.frozen.expire",
      "isDefault": false,
      "path": "event:/SFX/Effects/frozen/expire",
      "category": "impact",
      "files": [
        "kenney_impact-sounds/Audio/impactGlass_medium_000.ogg",
        "kenney_impact-sounds/Audio/impactGlass_medium_001.ogg",
        "kenney_impact-sounds/Audio/impactGlass_medium_002.ogg",
        "kenney_impact-sounds/Audio/impactGlass_medium_003.ogg",
        "kenney_impact-sounds/Audio/impactGlass_medium_004.ogg"
      ]
    },
    {
      "key": "relic.light_shepherd.cast",
      "isDefault": false,
      "path": "event:/SFX/Relics/light_shepherd/cast",
      "category": "tonal",
      "files": [
        "RPG_Essentials_Free/8_Buffs_Heals_SFX/30_Revive_03.wav"
      ]
    },
    {
      "key": "relic.whirl_monk.cast",
      "isDefault": false,
      "path": "event:/SFX/Relics/whirl_monk/cast",
      "category": "whoosh",
      "files": [
        "RPG_Essentials_Free/12_Player_Movement_SFX/88_Teleport_02.wav"
      ]
    },
    {
      "key": "effect.vortex_entry.apply",
      "isDefault": false,
      "path": "event:/SFX/Effects/vortex_entry/apply",
      "category": "whoosh",
      "files": [
        "RPG_Essentials_Free/12_Player_Movement_SFX/88_Teleport_02.wav"
      ]
    },
    {
      "key": "relic.assassin.cast",
      "isDefault": false,
      "path": "event:/SFX/Relics/assassin/cast",
      "category": "whoosh",
      "files": [
        "RPG_Essentials_Free/8_Atk_Magic_SFX/25_Wind_01.wav"
      ]
    },
    {
      "key": "feel.kill.stinger",
      "isDefault": false,
      "path": "event:/SFX/Feel/kill",
      "category": "stinger",
      "files": [
        "kenney_impact-sounds/Audio/impactBell_heavy_000.ogg",
        "kenney_impact-sounds/Audio/impactBell_heavy_001.ogg",
        "kenney_impact-sounds/Audio/impactBell_heavy_002.ogg",
        "kenney_impact-sounds/Audio/impactBell_heavy_003.ogg",
        "kenney_impact-sounds/Audio/impactBell_heavy_004.ogg"
      ]
    },
    {
      "key": "feel.heavy_hit.hit",
      "isDefault": false,
      "path": "event:/SFX/Feel/heavy_hit",
      "category": "impact",
      "files": [
        "kenney_impact-sounds/Audio/impactPunch_heavy_000.ogg",
        "kenney_impact-sounds/Audio/impactPunch_heavy_001.ogg",
        "kenney_impact-sounds/Audio/impactPunch_heavy_002.ogg",
        "kenney_impact-sounds/Audio/impactPunch_heavy_003.ogg",
        "kenney_impact-sounds/Audio/impactPunch_heavy_004.ogg"
      ]
    },
    {
      "key": "feel.death_shatter.death",
      "isDefault": false,
      "path": "event:/SFX/Feel/death_shatter",
      "category": "impact",
      "files": [
        "kenney_impact-sounds/Audio/impactGlass_heavy_000.ogg",
        "kenney_impact-sounds/Audio/impactGlass_heavy_001.ogg",
        "kenney_impact-sounds/Audio/impactGlass_heavy_002.ogg",
        "kenney_impact-sounds/Audio/impactGlass_heavy_003.ogg",
        "kenney_impact-sounds/Audio/impactGlass_heavy_004.ogg"
      ]
    },
    {
      "key": "ui.pause.ui",
      "isDefault": false,
      "path": "event:/SFX/UI/pause",
      "category": "ui",
      "files": [
        "RPG_Essentials_Free/10_UI_Menu_SFX/092_Pause_04.wav"
      ]
    },
    {
      "key": "ui.resume.ui",
      "isDefault": false,
      "path": "event:/SFX/UI/resume",
      "category": "ui",
      "files": [
        "RPG_Essentials_Free/10_UI_Menu_SFX/098_Unpause_04.wav"
      ]
    },
    {
      "key": "ui.deploy_place.ui",
      "isDefault": false,
      "path": "event:/SFX/UI/deploy_place",
      "category": "ui",
      "files": [
        "RPG_Essentials_Free/10_UI_Menu_SFX/070_Equip_10.wav"
      ]
    },
    {
      "key": "battle.start.stinger",
      "isDefault": false,
      "path": "event:/Stingers/battle_start",
      "category": "stinger",
      "files": [
        "RPG_Essentials_Free/10_Battle_SFX/55_Encounter_02.wav"
      ]
    },
    {
      "key": "battle.victory.stinger",
      "isDefault": false,
      "path": "event:/Stingers/victory",
      "category": "stinger",
      "files": [
        "RPG_Essentials_Free/10_UI_Menu_SFX/013_Confirm_03.wav"
      ]
    },
    {
      "key": "battle.defeat.stinger",
      "isDefault": false,
      "path": "event:/Stingers/defeat",
      "category": "stinger",
      "files": [
        "RPG_Essentials_Free/10_UI_Menu_SFX/033_Denied_03.wav"
      ]
    }
  ]
};

    var logLines = [];
    function log(status, subject, reason) {
        logLines.push(status + ": " + subject + (reason ? " (" + reason + ")" : ""));
    }
    function flush() {
        try {
            var f = studio.system.getFile(LOG_PATH);
            f.open(studio.system.openMode.WriteOnly);
            f.writeText(logLines.join("\n") + "\n");
            f.close();
        } catch (e) { /* nothing we can do headless */ }
    }

    log("STARTED", "populate", "");
    flush();

    function findByName(modelType, name) {
        var all = modelType.findInstances();
        for (var i = 0; i < all.length; i++) if (all[i].name === name) return all[i];
        return null;
    }

    function findOrCreateBank(name) {
        var b = findByName(studio.project.model.Bank, name);
        if (b) return b;
        b = studio.project.create("Bank");
        b.name = name;
        log("BANK", name, "created isValid=" + b.isValid);
        return b;
    }

    function ensureEventFolder(folderPath) {
        var parent = studio.project.workspace.masterEventFolder;
        if (!folderPath) return parent;
        var parts = folderPath.split("/");
        for (var i = 0; i < parts.length; i++) {
            var name = parts[i];
            var found = null;
            var kids = parent.items || [];
            for (var k = 0; k < kids.length; k++) {
                if (kids[k].isOfExactType && kids[k].isOfExactType("EventFolder") && kids[k].name === name) { found = kids[k]; break; }
            }
            if (!found) { found = studio.project.create("EventFolder"); found.name = name; found.folder = parent; }
            parent = found;
        }
        return parent;
    }

    function parseEventPath(path) {
        var rel = path.replace(/^event:\//, "");
        var lastSlash = rel.lastIndexOf("/");
        return { folder: lastSlash !== -1 ? rel.substring(0, lastSlash) : "", name: lastSlash !== -1 ? rel.substring(lastSlash + 1) : rel };
    }

    function destroyExistingEvent(name, folder) {
        var events = studio.project.model.Event.findInstances();
        for (var i = 0; i < events.length; i++) {
            if (events[i].name === name && events[i].folder === folder) { events[i].isDestroyed = true; log("REBUILD", name, "removed existing"); }
        }
    }

    function findOrCreateBus(name) {
        try {
            var g = findByName(studio.project.model.MixerGroup, name);
            if (g) return g;
            g = studio.project.create("MixerGroup");
            g.name = name;
            try { g.output = studio.project.workspace.masterBus; } catch (e) {}
            log("BUS", name, "created");
            return g;
        } catch (e) { log("BUS", name, "skipped: " + e); return null; }
    }

    try {
        var sourceRoot = MANIFEST.sourceRoot;
        var bank = findOrCreateBank(MANIFEST.bank || "SFX");
        log("INFO", "bank ready", MANIFEST.bank || "SFX");
        flush();

        if (MANIFEST.buses) {
            for (var busKey in MANIFEST.buses) if (MANIFEST.buses.hasOwnProperty(busKey)) findOrCreateBus(busKey);
        }
        flush();

        var events = MANIFEST.events || [];
        var built = 0, failed = 0;

        for (var e = 0; e < events.length; e++) {
            var entry = events[e];
            var cat = (MANIFEST.categories && MANIFEST.categories[entry.category]) || {};
            var parsed = parseEventPath(entry.path);
            var folder = ensureEventFolder(parsed.folder);
            destroyExistingEvent(parsed.name, folder);

            var event = studio.project.create("Event");
            event.name = parsed.name;
            event.folder = folder;
            var track = event.addGroupTrack();

            var assets = [];
            for (var fi = 0; fi < entry.files.length; fi++) {
                var full = sourceRoot + "/" + entry.files[fi];
                var asset = studio.project.importAudioFile(full);
                if (asset) assets.push(asset); else log("FAILED", full, "import failed");
            }
            if (assets.length === 0) { event.isDestroyed = true; failed++; log("FAILED", entry.path, "no audio"); flush(); continue; }

            var length = 0;
            for (var a = 0; a < assets.length; a++) length = Math.max(length, assets[a].length || 1);
            if (length <= 0) length = 1;

            if (assets.length > 1) {
                var multi = track.addSound(event.timeline, "MultiSound", 0, length);
                multi.name = parsed.name;
                for (var m = 0; m < assets.length; m++) {
                    var single = studio.project.create("SingleSound");
                    single.audioFile = assets[m];
                    single.owner = multi;
                }
            } else {
                var sound = track.addSound(event.timeline, "SingleSound", 0, length);
                sound.audioFile = assets[0];
                sound.name = parsed.name;
            }

            // .add() is the only relationship method on this FMOD version (no .isEmpty/.length);
            // in-process build below is what makes it persist. Plain add, no guard.
            try { event.relationships.banks.add(bank); }
            catch (be) { log("WARN", entry.path, "bank assign failed: " + be); }
            if (cat.maxInstances) { try { event.automatableProperties.maxVoices = cat.maxInstances; } catch (mv) { log("WARN", entry.path, "maxVoices failed: " + mv); } }

            built++;
            log("OK", entry.path, assets.length + " file(s), cat=" + entry.category);
            flush();
        }

        log("SAVING", "project", "");
        flush();
        studio.project.save();
        // Bank building is a SEPARATE step (in-process build() is unreliable on this version):
        //   fmodstudiocl -build -ignore-warnings -export-guids project.fspro
        // (-ignore-warnings needed: events aren't routed to a custom bus yet — that's the GUI pass).
        log("DONE", "populate", "built " + built + ", failed " + failed + " — now run fmodstudiocl -build -ignore-warnings");
        flush();
    } catch (err) {
        log("FATAL", "populate", "" + err);
        flush();
    }
})();
