var AllyProximityDamageBonusComponent_8cs =
[
    [ "Guildmaster.Combat.Effects.Components.AllyProximityDamageBonusComponent", "classGuildmaster_1_1Combat_1_1Effects_1_1Components_1_1AllyProximityDamageBonusComponent.html", "classGuildmaster_1_1Combat_1_1Effects_1_1Components_1_1AllyProximityDamageBonusComponent" ]
];